import { Geist, Geist_Mono ,Cinzel} from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
  import {LenisProvider} from "@/components/SmoothScroll";
import WhatsappSvg from "@/components/ icons/WhatsappSvg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-100">
        <LenisProvider />
        <header className="sticky z-50 top-0 right-0 left-0">
          <nav>
            <Nav />
          </nav>
        </header>
        {children}
        <div className='fixed bottom-10 right-5 z-50'><WhatsappSvg width={50} height={50} /></div>
        <Footer />


      </body>
    </html>
  );
}
